### ISSUE TITLE
To provide a Chinese translation for the document.

### ISSUE THREAD

**Issue by fcdjds** [neoforged/Documentation#152]
Hello everyone,
The automatic translation to Chinese provided by the browser while viewing the document is not satisfactory. Therefore, I would like to contribute to the project by translating the document into Chinese to the best of my ability, but I'm unsure how to proceed. I would like to ask for some guidance. Should I first fork and clone the repository and then submit my changes? However, I want the Chinese translation to have its own separate page.

**Comment by IchHabeHunger54** [comment]
There is a pinned issue covering this: #131
And there are also two existing pull requests for a Chinese version: #19 (I assume Traditional Chinese) and #67 (Simplified Chinese).

The short version is that we lack the technical setup for multiple languages, and as well as proofreaders. To my knowledge, we do not have a single Chinese-speaking version on the team. While we do appreciate your interest in this, we cannot currently provide it.

All that being said, you can of course fork the repository and host the Chinese docs yourself. Please understand that due to technical and lack-of-proofreading reasons, we currently cannot have translated docs of any kind.
