### ISSUE TITLE
Clarifications needed to 'change the name of a mod' in "Getting Started with NeoForge"

### ISSUE THREAD

**Issue by Veltarden** [neoforged/Documentation#63]
So, I'm starting in minecraft modding, and found it very unclear when trying to change the name of my mod. As it reads on the document, on the section "Customizing Your Mod Information"

_"Many of the **basic properties** of your mod **can be changed in the gradle.properties file**. This includes basic things like the **mod name** or the mod version."_

Further by investigating, you stumble across mod files and find the definition of the property "mod_id"

_"The id of your mod. This should be something unique and memorable, as having two mods with the same id will prevent the game from loading. The mod id shows up in a lot of places, for example as the namespace for all your registered things, or as the namespace for your resource and data packs."_

One starting would think that in order to change the mod name you would only need to change this variable, but it turns out that there are more elements that interfere when building the mod and are related to the name, so if you only changed that property, it would cause trouble for mods to properly build.

Might be redundant for some but wouldn't it be more clear to say or suggest in the for example that in order to change the name of the mod, there are other properties that need to be changed properly?
For example, in the definition of "mod_id":

_"Note that this is not the only property related to the mod name, only changing this variable can create issues"._

Regardless of that issue, thanks in advance for the support.

**Comment by IchHabeHunger54** [comment]
Hello, sorry for the late response, this issue kinda went under the radar.

The mod id is explicitly _not_ the mod name. The mod name (or to be more exact, mod display name) is a property that is independent from the mod id by design. Changing the mod id in the MDK's gradle.properties should be enough to change all occurences of the mod id in the project. If that is not the case, this is likely a bug in the MDK. To diagnose this further, we would kindly need more information than "the mod fails to build".

**Comment by IchHabeHunger54** [comment]
Ater pointed me towards the `@Mod`-annotated class on Discord, which needs the parameter changed to the mod id mentioned. I completely forgot about that, and I will add that in a moment. Are there other places I forgot about?
